/**
 * Auth Types
 */
// Reset redux store Types
export const RESET_STORE = 'RESET_STORE';
// Set User Data Types
export const SET_USER_DATA = 'SET_USER_DATA';
// Current User Types
export const GET_CURRENT_USER_START = 'GET_CURRENT_USER_START';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE';
// Login Types
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
// Sign Up Types
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
// Forgot password Types
export const FORGOT_PASSWORD_START = 'FORGOT_PASSWORD_START';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
// Google Types
export const GOOGLE_SIGIN_START = 'GOOGLE_SIGIN_START';
export const GOOGLE_SIGIN_SUCCESS = 'GOOGLE_SIGIN_SUCCESS';
export const GOOGLE_SIGIN_FAILURE = 'GOOGLE_SIGIN_FAILURE';
// Facebook Types
export const FACEBOOK_SIGIN_START = 'FACEBOOK_SIGIN_START';
export const FACEBOOK_SIGIN_SUCCESS = 'FACEBOOK_SIGIN_SUCCESS';
export const FACEBOOK_SIGIN_FAILURE = 'FACEBOOK_SIGIN_FAILURE';
// Apple Types
export const APPLE_SIGIN_START = 'APPLE_SIGIN_START';
export const APPLE_SIGIN_SUCCESS = 'APPLE_SIGIN_SUCCESS';
export const APPLE_SIGIN_FAILURE = 'APPLE_SIGIN_FAILURE';
// Edit profile Types
export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';
// Add Address Types
export const ADD_ADDRESS = 'ADD_ADDRESS';
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
export const ADD_ADDRESS_FAILURE = 'ADD_ADDRESS_FAILURE';
// Interests Types
export const UPDATE_INTERESTS = 'UPDATE_INTERESTS';
export const UPDATE_INTERESTS_SUCCESS = 'UPDATE_INTERESTS_SUCCESS';
export const UPDATE_INTERESTS_FAILURE = 'UPDATE_INTERESTS_FAILURE';
// Product Size Types
export const GET_PRODUCT_SIZES = 'GET_PRODUCT_SIZES';
export const GET_PRODUCT_SIZES_SUCCESS = 'GET_PRODUCT_SIZES_SUCCESS';
export const GET_PRODUCT_SIZES_FAILURE = 'GET_PRODUCT_SIZES_FAILURE';
// Product Style Types
export const GET_PRODUCT_STYLES = 'GET_PRODUCT_STYLES';
export const GET_PRODUCT_STYLES_SUCCESS = 'GET_PRODUCT_STYLES_SUCCESS';
export const GET_PRODUCT_STYLES_FAILURE = 'GET_PRODUCT_STYLES_FAILURE';
// Product Designer Types
export const GET_PRODUCT_DESIGNERS = 'GET_PRODUCT_DESIGNERS';
export const GET_PRODUCT_DESIGNERS_SUCCESS = 'GET_PRODUCT_DESIGNERS_SUCCESS';
export const GET_PRODUCT_DESIGNERS_FAILURE = 'GET_PRODUCT_DESIGNERS_FAILURE';
// Edit Address Types
export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const EDIT_ADDRESS_SUCCESS = 'EDIT_ADDRESS_SUCCESS';
export const EDIT_ADDRESS_FAILURE = 'EDIT_ADDRESS_FAILURE';
// Card Set Up Intent Types
export const CARD_SETUP_INTENT = 'CARD_SETUP_INTENT';
export const CARD_SETUP_INTENT_SUCCESS = 'CARD_SETUP_INTENT_SUCCESS';
export const CARD_SETUP_INTENT_FAILURE = 'CARD_SETUP_INTENT_FAILURE';
// Add Card Types
export const ADD_CARD = 'ADD_CARD';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_FAILURE = 'ADD_CARD_FAILURE';
// Get Card Types
export const GET_USER_CARDS = 'GET_USER_CARDS';
export const GET_USER_CARDS_SUCCESS = 'GET_USER_CARDS_SUCCESS';
export const GET_USER_CARDS_FAILURE = 'GET_USER_CARDS_FAILURE';
// Verify Email Types
export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';
// Send Otp Types
export const SEND_EMAIL_VERIFICATION_OTP = 'SEND_EMAIL_VERIFICATION_OTP';
export const SEND_EMAIL_VERIFICATION_OTP_SUCCESS =
  'SEND_EMAIL_VERIFICATION_OTP_SUCCESS';
export const SEND_EMAIL_VERIFICATION_OTP_FAILURE =
  'SEND_EMAIL_VERIFICATION_OTP_FAILURE';
// Verify Forgot Password otp Types
export const VERIFY_FORGOT_PASSWORD_OTP = 'VERIFY_FORGOT_PASSWORD_OTP';
export const VERIFY_FORGOT_PASSWORD_OTP_SUCCESS =
  'VERIFY_FORGOT_PASSWORD_OTP_SUCCESS';
export const VERIFY_FORGOT_PASSWORD_OTP_FAILURE =
  'VERIFY_FORGOT_PASSWORD_OTP_FAILURE';
// Set New Password otp Types
export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD';
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_FAILURE = ' SET_NEW_PASSWORD_FAILURE';
// get Faqs Types
export const GET_FAQS = 'GET_FAQS';
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS';
export const GET_FAQS_FAILURE = 'GET_FAQS_FAILURE';
// get Site Settings Types
export const GET_SITE_SETTING = 'GET_SITE_SETTING';
export const GET_SITE_SETTING_SUCCESS = 'GET_SITE_SETTING_SUCCESS';
export const GET_SITE_SETTING_FAILURE = 'GET_SITE_SETTING_FAILURE';
// get Categories Types
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';
// get Sub Categories Types
export const GET_SUB_CATEGORIES = 'GET_SUB_CATEGORIES';
export const GET_SUB_CATEGORIES_SUCCESS = 'GET_SUB_CATEGORIES_SUCCESS';
export const GET_SUB_CATEGORIES_FAILURE = 'GET_SUB_CATEGORIES_FAILURE';
// get Designers Types
export const GET_DESIGNERS = 'GET_DESIGNERS';
export const GET_DESIGNERS_SUCCESS = 'GET_DESIGNERS_SUCCESS';
export const GET_DESIGNERS_FAILURE = 'GET_DESIGNERS_FAILURE';
// get Sizes Of Category Types
export const GET_SIZES = 'GET_SIZES';
export const GET_SIZES_SUCCESS = 'GET_SIZES_SUCCESS';
export const GET_SIZES_FAILURE = 'GET_SIZES_FAILURE';
// get Condition Types
export const GET_CONDITIONS = 'GET_CONDITIONS';
export const GET_CONDITIONS_SUCCESS = 'GET_CONDITIONS_SUCCESS';
export const GET_CONDITIONS_FAILURE = 'GET_CONDITIONS_FAILURE';
// get Product shipping type(like... domestic, nationwide or worldwide) Types
export const GET_PRODUCT_SHIPPING_TYPE = 'GET_PRODUCT_SHIPPING_TYPE';
export const GET_PRODUCT_SHIPPING_TYPE_SUCCESS =
  'GET_PRODUCT_SHIPPING_TYPE_SUCCESS';
export const GET_PRODUCT_SHIPPING_TYPE_FAILURE =
  'GET_PRODUCT_SHIPPING_TYPE_FAILURE';
// pre Signed URL Types
export const PRE_SIGNED_URL = 'PRE_SIGNED_URL';
export const PRE_SIGNED_URL_SUCCESS = 'PRE_SIGNED_URL_SUCCESS';
export const PRE_SIGNED_URL_FAILURE = 'PRE_SIGNED_URL_FAILURE';
// create Product(Listing Items) Types
export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
// get Product Types
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
// Reset Product Types
export const RESET_PRODUCT = 'RESET_PRODUCT';
//Reset PreSigned Url
export const RESET_PRE_SIGNED_URL = 'RESET_PRE_SIGNED_URL';
// get Liked products of user
export const GET_LIKED_PRODUCTS = 'GET_LIKED_PRODUCTS';
export const GET_LIKED_PRODUCTS_SUCCESS = 'GET_LIKED_PRODUCTS_SUCCESS';
export const GET_LIKED_PRODUCTS_FAILURE = 'GET_LIKED_PRODUCTS_FAILURE';
// get current user products Types
export const GET_CURRENT_USER_PRODUCTS = 'GET_CURRENT_USER_PRODUCTS';
export const GET_CURRENT_USER_PRODUCTS_SUCCESS =
  'GET_CURRENT_USER_PRODUCTS_SUCCESS';
export const GET_CURRENT_USER_PRODUCTS_FAILURE =
  'GET_CURRENT_USER_PRODUCTS_FAILURE';
// get user profile by id Types
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';
// create like product of user
export const CREATE_LIKE_PRODUCT = 'CREATE_LIKE_PRODUCT';
export const CREATE_LIKE_PRODUCT_SUCCESS = 'CREATE_LIKE_PRODUCT_SUCCESS';
export const CREATE_LIKE_PRODUCT_FAILURE = 'CREATE_LIKE_PRODUCT_FAILURE';
// delete like product of user
export const DELETE_LIKED_PRODUCT = 'DELETE_LIKED_PRODUCT';
export const DELETE_LIKED_PRODUCT_SUCCESS = 'DELETE_LIKED_PRODUCT_SUCCESS';
export const DELETE_LIKED_PRODUCT_FAILURE = 'DELETE_LIKED_PRODUCT_FAILURE';
// follow user Types
export const FOLLOW_START = 'FOLLOW_START';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const FOLLOW_FAILURE = 'FOLLOW_FAILURE';
// unfollow user Types
export const UNFOLLOW_START = 'UNFOLLOW_START';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';
export const UNFOLLOW_FAILURE = 'UNFOLLOW_FAILURE';
// get current user cart Types
export const GET_CURRENT_USER_CART = 'GET_CURRENT_USER_CART';
export const GET_CURRENT_USER_CART_SUCCESS = 'GET_CURRENT_USER_CART_SUCCESS';
export const GET_CURRENT_USER_CART_FAILURE = 'GET_CURRENT_USER_CART_FAILURE';
// Add product to cart Types
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const ADD_PRODUCT_TO_CART_SUCCESS = 'ADD_PRODUCT_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART_FAILURE = 'ADD_PRODUCT_TO_CART_FAILURE';
// get user policies Types
export const GET_CLOSET_POLICIES = 'GET_CLOSET_POLICIES';
export const GET_CLOSET_POLICIES_SUCCESS = 'GET_CLOSET_POLICIES_SUCCESS';
export const GET_CLOSET_POLICIES_FAILURE = 'GET_CLOSET_POLICIES_FAILURE';
// get turn on/off notification Types
export const TURN_ON_OFF_NOTIFICATION = 'TURN_ON_OFF_NOTIFICATION';
export const TURN_ON_OFF_NOTIFICATION_SUCCESS =
  'TURN_ON_OFF_NOTIFICATION_SUCCESS';
export const TURN_ON_OFF_NOTIFICATION_FAILURE =
  'TURN_ON_OFF_NOTIFICATION_FAILURE';
// remove product from cart Types
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const REMOVE_PRODUCT_FROM_CART_SUCCESS =
  'REMOVE_PRODUCT_FROM_CART_SUCCESS';
export const REMOVE_PRODUCT_FROM_CART_FAILURE =
  'REMOVE_PRODUCT_FROM_CART_FAILURE';
// get product Types
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO';
export const GET_PRODUCT_INFO_SUCCESS = 'GET_PRODUCT_INFO_SUCCESS';
export const GET_PRODUCT_INFO_FAILURE = 'GET_PRODUCT_INFO_FAILURE';
// get Feed Types
export const GET_FEED = 'GET_FEED';
export const GET_FEED_SUCCESS = 'GET_FEED_SUCCESS';
export const GET_FEED_FAILURE = 'GET_FEED_FAILURE';
// logout User Types
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';
// create Order Types
export const CREATE_ORDER = 'CREATE_ORDER';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAILURE = 'CREATE_ORDER_FAILURE';
// get Order Types
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';
// get Order Info Types
export const GET_ORDER_INFO = 'GET_ORDER_INFO';
export const GET_ORDER_INFO_SUCCESS = 'GET_ORDER_INFO_SUCCESS';
export const GET_ORDER_INFO_FAILURE = 'GET_ORDER_INFO_FAILURE';
// get Order Info Types
export const GET_CLOSET_ORDER_INFO = 'GET_CLOSET_ORDER_INFO';
export const GET_CLOSET_ORDER_INFO_SUCCESS = 'GET_CLOSET_ORDER_INFO_SUCCESS';
export const GET_CLOSET_ORDER_INFO_FAILURE = 'GET_CLOSET_ORDER_INFO_FAILURE';
// Update Product Types
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';
// Update Shipping Types
export const UPDATE_SHIPPING = 'UPDATE_SHIPPING';
export const UPDATE_SHIPPING_SUCCESS = 'UPDATE_SHIPPING_SUCCESS';
export const UPDATE_SHIPPING_FAILURE = 'UPDATE_SHIPPING_FAILURE';
// Get Occasions Types
export const GET_OCCASION = 'GET_OCCASION';
export const GET_OCCASION_SUCCESS = 'GET_OCCASION_SUCCESS';
export const GET_OCCASION_FAILURE = 'GET_OCCASION_FAILURE';
// Get most liked products Types
export const GET_MOST_LIKED_PRODUCT = 'GET_MOST_LIKED_PRODUCT';
export const GET_MOST_LIKED_PRODUCT_SUCCESS = 'GET_MOST_LIKED_PRODUCT_SUCCESS';
export const GET_MOST_LIKED_PRODUCT_FAILURE = 'GET_MOST_LIKED_PRODUCT_FAILURE';
// Get recent search Types
export const GET_RECENT_SEARCH = 'GET_RECENT_SEARCH';
export const GET_RECENT_SEARCH_SUCCESS = 'GET_RECENT_SEARCH_SUCCESS';
export const GET_RECENT_SEARCH_FAILURE = 'GET_RECENT_SEARCH_FAILURE';
// Get saved search Types
export const GET_SAVED_SEARCH = 'GET_SAVED_SEARCH';
export const GET_SAVED_SEARCH_SUCCESS = 'GET_SAVED_SEARCH_SUCCESS';
export const GET_SAVED_SEARCH_FAILURE = 'GET_SAVED_SEARCH_FAILURE';
// Get searched products Types
export const GET_SEARCHED_PRODUCTS = 'GET_SEARCHED_PRODUCTS';
export const GET_SEARCHED_PRODUCTS_SUCCESS = 'GET_SEARCHED_PRODUCTS_SUCCESS';
export const GET_SEARCHED_PRODUCTS_FAILURE = 'GET_SEARCHED_PRODUCTS_FAILURE';
// get Order For Current Closet ( Your Transaction ) Types
export const GET_ORDERS_FOR_CURRENT_CLOSET = 'GET_ORDERS_FOR_CURRENT_CLOSET';
export const GET_ORDERS_FOR_CURRENT_CLOSET_SUCCESS =
  'GET_ORDERS_FOR_CURRENT_CLOSET_SUCCESS';
export const GET_ORDERS_FOR_CURRENT_CLOSET_FAILURE =
  'GET_ORDERS_FOR_CURRENT_CLOSET_FAILURE';
// get Renter Options Types
export const GET_RENTER_OPTIONS = 'GET_RENTER_OPTIONS';
export const GET_RENTER_OPTIONS_SUCCESS = 'GET_RENTER_OPTIONS_SUCCESS';
export const GET_RENTER_OPTIONS_FAILURE = 'GET_RENTER_OPTIONS_FAILURE';
// Get brands we love types
export const GET_BRANDS_WE_LOVE_PRODUCTS = 'GET_BRANDS_WE_LOVE_PRODUCTS';
export const GET_BRANDS_WE_LOVE_PRODUCTS_SUCCESS =
  'GET_BRANDS_WE_LOVE_PRODUCTS_SUCCESS';
export const GET_BRANDS_WE_LOVE_PRODUCTS_FAILURE =
  'GET_BRANDS_WE_LOVE_PRODUCTS_FAILURE';
// get Buyer Options Types
export const GET_BUYER_OPTIONS = 'GET_BUYER_OPTIONS';
export const GET_BUYER_OPTIONS_SUCCESS = 'GET_BUYER_OPTIONS_SUCCESS';
export const GET_BUYER_OPTIONS_FAILURE = 'GET_BUYER_OPTIONS_FAILURE';
// get Lender Options Types
export const GET_LENDER_OPTIONS = 'GET_LENDER_OPTIONS';
export const GET_LENDER_OPTIONS_SUCCESS = 'GET_LENDER_OPTIONS_SUCCESS';
export const GET_LENDER_OPTIONS_FAILURE = 'GET_LENDER_OPTIONS_FAILURE';
// get Seller Options Types
export const GET_SELLER_OPTIONS = 'GET_SELLER_OPTIONS';
export const GET_SELLER_OPTIONS_SUCCESS = 'GET_SELLER_OPTIONS_SUCCESS';
export const GET_SELLER_OPTIONS_FAILURE = 'GET_SELLER_OPTIONS_FAILURE';
// get Rate Order Types
export const RATE_ORDER = 'RATE_ORDER';
export const RATE_ORDER_SUCCESS = 'RATE_ORDER_SUCCESS';
export const RATE_ORDER_FAILURE = 'RATE_ORDER_FAILURE';
// get Order Types
export const UPDATE_ORDER_RATING = 'UPDATE_ORDER_RATING';
export const UPDATE_ORDER_RATING_SUCCESS = 'UPDATE_ORDER_RATING_SUCCESS';
export const UPDATE_ORDER_RATING_FAILURE = 'UPDATE_ORDER_RATING_FAILURE';
// get My Reviews Types
export const GET_MY_REVIEWS = 'GET_MY_REVIEWS';
export const GET_MY_REVIEWS_SUCCESS = 'GET_MY_REVIEWS_SUCCESS';
export const GET_MY_REVIEWS_FAILURE = 'GET_MY_REVIEWS_FAILURE';
// Clear messages data Types
export const CLEAR_MESSAGES_DATA = 'CLEAR_MESSAGES_DATA';
// Get messages Types
export const GET_MESSAGE = 'GET_MESSAGE';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const GET_MESSAGE_FAILURE = 'GET_MESSAGE_FAILURE';
// Add new messages Types
export const ADD_NEW_MESSAGE = 'ADD_NEW_MESSAGE';
//Set Room Id TYpes
export const SET_ROOM_ID = 'SET_ROOM_ID';
//Remove Room Id Types
export const REMOVE_ROOM_ID = 'REMOVE_ROOM_ID';
// Create messages Types
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const CREATE_MESSAGE_SUCCESS = 'CREATE_MESSAGE_SUCCESS';
export const CREATE_MESSAGE_FAILURE = 'CREATE_MESSAGE_FAILURE';
// Get rooms Types
export const GET_ROOMS = 'GET_ROOMS';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILURE = 'GET_ROOMS_FAILURE';
// Create room Types
export const CREATE_ROOM = 'CREATE_ROOM';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const CREATE_ROOM_FAILURE = 'CREATE_ROOM_FAILURE';
// Approve reviewed imaged Types
export const APPROVE_REVIEWED_IMAGES = 'APPROVE_REVIEWED_IMAGES';
export const APPROVE_REVIEWED_IMAGES_SUCCESS =
  'APPROVE_REVIEWED_IMAGES_SUCCESS';
export const APPROVE_REVIEWED_IMAGES_FAILURE =
  'APPROVE_REVIEWED_IMAGES_FAILURE';
// Get Product Ratings Types
export const GET_PRODUCT_RATINGS = 'GET_PRODUCT_RATINGS';
export const GET_PRODUCT_RATINGS_SUCCESS = 'GET_PRODUCT_RATINGS_SUCCESS';
export const GET_PRODUCT_RATINGS_FAILURE = 'GET_PRODUCT_RATINGS_FAILURE';
// Find Users with phone numbers Types
export const FIND_USERS_WITH_PHONE_NUMBERS = 'FIND_USERS_WITH_PHONE_NUMBERS';
export const FIND_USERS_WITH_PHONE_NUMBERS_SUCCESS =
  'FIND_USERS_WITH_PHONE_NUMBERS_SUCCESS';
export const FIND_USERS_WITH_PHONE_NUMBERS_FAILURE =
  'FIND_USERS_WITH_PHONE_NUMBERS_FAILURE';
// Delete saved search Types
export const DELETE_SAVED_SEARCH = 'DELETE_SAVED_SEARCH';
export const DELETE_SAVED_SEARCH_SUCCESS = 'DELETE_SAVED_SEARCH_SUCCESS';
export const DELETE_SAVED_SEARCH_FAILURE = 'DELETE_SAVED_SEARCH_FAILURE';
// Get product color Types
export const GET_PRODUCT_COLOR = 'GET_PRODUCT_COLOR';
export const GET_PRODUCT_COLOR_SUCCESS = 'GET_PRODUCT_COLOR_SUCCESS';
export const GET_PRODUCT_COLOR_FAILURE = 'GET_PRODUCT_COLOR_FAILURE';
