export const strings = {
  loginTitle: 'LOGIN',
  signupTitle: 'SIGN UP',
  signup: 'Sign Up',
  emailOrPhoneNumber: 'EMAIL OR PHONE NUMBER',
  email: 'EMAIL',
  //firstName: 'firstName',
  unitedStates: 'UNITED STATES',
  janeDoe: 'JANE DOE',
  janeUser: 'Jane Doe',
  janeUser1: '@janedoe',
  ratedUserCounter: '(20)',
  aptUnitEtc: 'APT, UNIT ETC.',
  receivePromotion: 'receivePromotion',
  password: 'PASSWORD',
  show: 'Show',
  hide: 'Hide',
  back: 'BACK',
  close: 'CLOSE',
  renting: 'RENTING',
  purchasing: 'PURCHASING',
  rentDateTime: 'APR 7-10, Delivery on  Apr 7 by 12pm',
  itemName: 'ITEM NAME',
  itemBrand: 'ITEM BRAND',
  size: 'SIZE',
  price1: '2350',
  price2: '80',
  price3: '1650',
  forgotPasswordTitle: 'FORGOT YOUR\nPASSWORD?',
  forgotPasswordDesc:
    'Please enter your email below and we will send you a link to reset your passwrod',
  forgotYourPassword: 'Forgot your password?',
  resetPasswordTitle: 'RESET YOUR\nPASSWORD',
  verifyForgotPasswordOtp: 'VERIFY FORGOT\nPASSWORD OTP',
  verifyYourEmail: 'VERIFY EMAIL',
  verifyOtp: 'VERIFY OTP',
  createGroup: 'CREATE GROUP',
  verifyEmailDesc: 'Please check your email and enter otp for verification',
  verifyForgotPasswordOtpDesc:
    'Please check your email and enter otp for forgot password otp verification',
  enterOtp: 'ENTER OTP',
  resetPasswordDesc:
    'Please enter your new password below. Your new password must contain:',
  resetPassDesc1: 'at least 8 characters',
  resetPassDesc2: 'at least one upper-case character',
  resetPassDesc3: 'at least one number',
  newPassword: 'NEW PASSWORD',
  reEnterNewPassword: 'RE-ENTER NEW PASSWORD',
  submitNewPassword: 'SUBMIT NEW PASSWORD',
  login: 'LOG IN',
  or: 'OR',
  x: 'x',
  signinWithFacebook: 'SIGN IN WITH FACEBOOK',
  signinWithGoogle: 'SIGN IN WITH GOOGLE',
  signinWithApple: 'SIGN IN WITH APPLE',
  name: 'NAME',
  receiveNewsletter:
    'I would like to receive your newsletter and other promotional information.',
  submit: 'SUBMIT',
  somethingWentWrong: 'Something went wrong!',
  codeSent: 'Code has been sent',
  pleaseTryAgain: 'Please try again.',
  pleaseVerifyEmailAndLogin: 'Please verify your email and login again.',
  resetMyPassword: 'RESET MY PASSWORD',
  invalidEmail: 'Invalid Email!',
  enterValidEmail: 'Please enter valid email.',
  emailEmpty: 'Email is empty!',
  enterYourEmail: 'Please enter your email.',
  nameEmpty: 'Name is empty!',
  enterYourName: 'Please enter your name.',
  passwordEmpty: 'Password is empty!',
  enterYourPassword: 'Please enter your password.',
  enterValidPassword: 'Please enter valid password.',
  editProfile: 'EDIT PROFILE',
  yourBag: 'YOUR BAG',
  myAddresses: 'MY ADDRESSES',
  addAddress: 'ADD ADDRESS',
  selectCountry: 'SELECT COUNTRY',
  streetAddress: 'STREET ADDRESS',
  aptUnit: 'APT, UNIT ETC.',
  city: 'CITY',
  saveAddress: 'SAVE ADDRESS',
  billingInformation: 'BILLING INFORMATION',
  savedCreditCards: 'SAVED CREDIT CARDS',
  addCard: 'ADD CARD',
  chase0123: 'CHASE...0123',
  expDate: 'EXP 2/20',
  bankAccountsLinked: 'BANK ACCOUNTS LINKED',
  add: 'ADD',
  paymentPreferences: 'PAYMENT PREFERENCES',
  directDeposite: 'DIRECT DEPOSITE',
  myCredit: 'MY CREDIT',
  editAddress: 'EDIT ADDRESS',
  lastName: 'LAST NAME',
  emailAddress: 'EMAIL ADDRESS',
  phoneNumber: 'PHONE NUMBER',
  editBio: 'EDIT BIO',
  update: 'UPDATE',
  firstNameEmpty: 'First name is empty!',
  aptOrUnitNumberEmpty: 'Apt or Unit number is empty!',
  enterAptOrUnitAddress: 'Please enter apt or unit number.',
  streetAddressEmpty: 'Street Address is empty!',
  enterStreetAddress: 'Please enter street address.',
  fullNameEmpty: 'Full name is empty!',
  enterYourFullName: 'Please enter your full name.',
  countryNameEmpty: 'Country name is empty!',
  countryNotSelected: 'Please Select country!',
  enterCountryName: 'Please enter country name.',
  cityNameEmpty: 'City name is empty!',
  enterCityName: 'Please enter city name.',
  stateNameEmpty: 'State name is empty!',
  enterStateName: 'Please enter state name.',
  zipCodeEmpty: 'Zip Code is empty!',
  enterZipCode: 'Please enter zip code.',
  enterYourFirstName: 'Please enter your first name.',
  lastNameEmpty: 'Last name is empty!',
  enterYourLastName: 'Please enter your last name.',
  phoneNumberEmpty: 'Phone number is empty!',
  enterYourPhoneNumber: 'Please enter your phone number.',
  bioEmpty: 'Bio is empty!',
  enterYourBio: 'Please enter your bio.',
  hijane: 'HI, JANE',
  editmyprofile: 'Edit my profile',
  myAccount: 'MY ACCOUNT',
  myHearts: 'My Hearts',
  previouslyRented: 'Previously Rented',
  sort: 'SORT',
  price: 'PRICE',
  minPrice: 'MIN PRICE',
  maxPrice: 'MAX PRICE',
  color: 'COLOR',
  colors: 'COLORS',
  designerTitle: 'DESIGNER',
  occasion: 'OCCASION',
  bodyType: 'BODY TYPE',
  weather: 'WEATHER',
  style: 'STYLE',
  recommended: 'Recommended',
  mostPopular: 'Most Popular',
  rentalHighToLow: 'Rental Price (High to Low)',
  rentalLowToHigh: 'Rental Price (Low to High)',
  retailHighToLow: 'Retail Price (High to Low)',
  retailLowToHigh: 'Retail Price (Low to High)',
  itemForSale: 'Items for Sale',
  itemForRent: 'Items for Rent',
  interestsAndSizes: 'Interests & Sizes',
  payment: 'PAYMENT',
  myAddress: 'My Addresses',
  savedAdresses: 'SAVED ADDRESSES',
  addressDetail: '1000 SANTA MONIKA',
  family: 'FAMILY',
  sorority: 'SORORITY',
  contactUs: 'CONTACT US',
  returnAddress: 'RETURN ADDRESS',
  orders: 'ORDERS',
  orderHistory: 'Order History',
  myReviews: 'My Reviews',
  community: 'COMMUNITY',
  yourCircle: 'Your Circles',
  inviteFriends: 'Invite Friends',
  support: 'SUPPORT',
  faq: 'FAQ',
  howChiaWorks: 'How Chia Works',
  needHelp: 'Need help?',
  includeSecurityBadges: 'INCLUDE SECURITY BADGES',
  verifyPayment: 'Verify Payment',
  verifyPhone: 'Verify Phone ',
  verifyEmail: 'Verify Email',
  verifyID: 'Verify ID',
  addressSavedSuccessfully: 'Address saved successfully',
  success: 'Success!',
  profileUpdatedSuccessfully: 'Profile update successfully.',
  styles: 'STYLES',
  editStyles: 'EDIT STYLES',
  designers: 'DESIGNERS',
  editDesigners: 'EDIT DESIGNERS',
  yourDesigners: 'YOUR DESIGNERS',
  yourSizes: 'YOUR SIZES',
  editSizes: 'EDIT SIZES',
  search: 'SEARCH',
  searchDesigners: 'SEARCH DESIGNERS',
  editYourSizes: 'EDIT YOUR SIZES',
  expiry: 'EXP',
  cardAddedSuccessfully: 'Card Added successfully',
  selectBillingAddress: 'SELECT BILLING ADDRESS',
  addNewAddress: 'ADD NEW',
  cardDetailEmpty: 'Card Details are empty!.',
  enterCardDetail: 'Please Add Card Details',
  howChiaWorksDesc:
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque elementum dolor consectetur neque interdum pretium.' +
    ' Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Proin nec velit quis purus tempus dapibus. ' +
    'Phasellus turpis sem, tempor ut arcu id, condimentum dignissim purus. Cras vehicula risus leo, vitae euismod magna facilisis at. ' +
    'Praesent rhoncus ac nulla eget vehicula. Mauris condimentum interdum scelerisque. Donec eu orci nec dui pellentesque vehicula.' +
    ' Interdum et malesuada fames ac ante ipsum primis in faucibus.' +
    ' Maecenas ullamcorper, mi a congue scelerisque, nisi nisi tempus elit, sed interdum orci nunc sit amet dolor.\n' +
    '\n' +
    'Nullam lacus lorem, consequat sed dolor eget, efficitur lobortis urna. Integer non tortor et lorem tincidunt finibus rutrum eu eros.' +
    ' Etiam arcu dui, laoreet eget faucibus id, imperdiet quis orci. Aenean sed libero vitae est pharetra tempus sed ac magna.' +
    ' Mauris finibus turpis vel varius imperdiet. Morbi pellentesque risus et mi aliquet vehicula. Etiam sollicitudin id dolor non luctus.' +
    ' Pellentesque vel orci volutpat, aliquam nunc in, fermentum nisi. Sed ut urna tincidunt lacus mollis efficitur nec placerat diam.\n' +
    '\n' +
    'Morbi lobortis ipsum sapien, eget pretium ante suscipit eu. In facilisis hendrerit purus vitae ultrices. ' +
    'Donec feugiat suscipit orci, rutrum commodo turpis sagittis vitae. Nunc vitae semper est. Curabitur eu tortor quis ipsum pulvinar gravida. ' +
    'Nulla porttitor vel justo vel fermentum. Cras ut lectus nec ex mattis gravida et in mi. Sed porttitor sapien in nibh lobortis pharetra.' +
    ' Donec ut lobortis diam. Vivamus vel maximus orci. Aliquam erat volutpat. Proin laoreet elit in mauris laoreet venenatis.',
  enterOTP: 'Please enter otp!',
  passwordMismatch: 'Password Mismatch!',
  enterSamePassword: 'Please enter same Password...',
  listing: 'LISTING',
  editPictures: 'EDIT PICTURES',
  itemDescription: 'ITEM DESCRIPTION',
  info: 'INFO',
  category: 'Category',
  subCategory: 'Subcategory',
  designer: 'Designer',
  condition: 'Condition',
  pricing: 'PRICING',
  rentalPricing: 'Rental Pricing',
  sellingPrice: 'Selling Price',
  originalRetailPrice: 'Original Retail Price',
  enhanceListing: 'ENHANCE YOUR LISTING',
  itemAvailability: 'ITEM AVAILABILITY',
  itemAvailableNow: 'Item is available now',
  itemAvailablePurchase: 'Item is available to purchase',
  selectUnavailableDates: 'Select Unavailable Dates',
  rentTo: 'Rent To',
  pickUpAvailable: 'Pick up available',
  pickupLocation: 'Pickup Location',
  dropoffAvailable: 'Drop-off available',
  dropoffAddedFee: 'Drop-off added fee',
  dropoffWithin: 'Drop-off within',
  samedayDeliveryAvailable: 'Same day delivery available',
  deliverWithChia: 'Deliver with CHIA',
  deliverMySelf: 'Arrange delivery myself',
  samedayDeliveryAddedFee: 'Same Day Delivery added Fee',
  deliverWith: 'Deliver with',
  standardShipping: 'Standard Shipping',
  shipNational: 'Ship National',
  shipWorldwide: 'Ship Worldwide',
  shipDomestic: 'Ship Domestic',
  addOns: 'ADD-ONS',
  requireDrycleaning: 'Require dry cleaning',
  addedDrycleaningFee: 'Added dry cleaning fee',
  requireAddonInsurance: 'Require add-on insurance',
  insuranceAddonFee: 'Insurance add-on fee',
  save: 'SAVE',
  inYourCloset: 'IN YOUR CLOSET',
  viewAll: 'VIEW ALL',
  receipts: 'RECEIPTS',
  viewAllPastTransation: 'View all past transactions',
  closetSetting: 'CLOSET SETTINGS',
  turnOnVactionMode: 'Turn on vaction mode',
  yourClodetPolicies: 'Your Closet Policies',
  availableTo: 'Available to',
  createNewCircle: 'CREATE NEW CIRCLE',
  yourPolocies: 'YOUR POLICIES',
  dryCleaning: 'Dry Cleaning',
  dryCleaningRequiredForAllItems: 'Dry-cleaning required for all items',
  dryCleaningRequiredForSomeItems:
    'Dry-cleaning requried for some items and i will specify which individually',
  idLikeToApproveAllrentalRequets: " I'd like to approve all rental requests",
  iWillHandleDryCleaningMyself: 'I’ll handle dry cleaning myself',
  rentalRequest: 'Rental Requests',
  iDontNeedToApprove: "I don't need to approve rental requests",
  shipping: 'Shipping',
  offerSameDayDelivery: 'Offer same day delivery',
  nationalShippingAvailable: 'National shipping available',
  reviews: 'REVIEWS',
  listerNotes: 'LISTER’S NOTES',
  purchase: 'PURCHASE',
  rentNow: 'RENT NOW',
  checkOutShipping: 'CHECKOUT: SHIPPING',
  firstName: 'FIRST NAME',
  address: 'ADDRESS',
  aptUnit: 'APT/UNIT',
  state: 'STATE',
  zipCode: 'ZIP CODE',
  sameAsBillingAddress: 'Same as billing address',
  phone: 'PHONE',
  saveAndContinue: 'SAVE & CONTINUE',
  fullName: 'FULL NAME',
  creditCardNumber: 'CREDIT CARD NUMBER',
  cvv: 'CVV',
  expDate: 'EXP DATE',
  billingAddress: 'BILLING ADDRESS',
  sameAsShippingAddress: 'Same as shipping address 1000 Santa Monica',
  checkOutBilling: 'CHECKOUT:  BILLING',
  checkoutConfirm: 'CHECKOUT: CONFIRM',
  shippingAddress: 'SHIPPING ADDRESS',
  edit: 'EDIT',
  deliveryDate: 'DELIVERY DATE',
  billing: 'BILLING',
  orderSubTotal: 'Order Subtotal',
  serviceFee: 'Service Fee',
  salesTax: 'Sales Tax',
  grandTotal: 'Grand Total',
  confirmOrder: 'CONFRIM ORDER',
  jane: 'HEY, JANE',
  browseAll: 'BROWSE ALL',
  new: 'NEW',
  mostWanted: 'MOST WANTED',
  myChia: 'MY CHIA',
  clothing: 'CLOTHING',
  browseByDesigner: 'BROWSE BY DESIGNER',
  browseByStyle: 'BROWSE BY STYLE',
  browseByOccasion: 'BROWSE BY OCCASION',
  browseByBodyType: 'BROWSE BY BODY TYPE',
  hearts: 'HEARTS',
  orderHistory: 'ORDER HISTORY',
  myProfile: 'MY PROFILE',
  bridal: 'BRIDAL',
  denim: 'BRIDAL',
  dresses: 'DRESSES',
  jacketsAndCoats: 'JACKETS & COATS',
  jumpsuitsAndRompers: 'JUMPSUITS & ROMPERS',
  loungeWear: 'LOUNGEWEAR',
  matchingSets: 'MATCHING SETS',
  pants: 'PANTS',
  shorts: 'SHORTS',
  skirts: 'SKIRTS',
  sweterAndknites: 'SWEATER & KNITS',
  swimSuits: 'SWIMSUITS, CAFTANS, & COVERUPS',
  bags: 'BAGS',
  shoes: 'SHOES',
  accessories: 'ACCESSORIES',
  activeWear: 'ACTIVEWEAR',
  designer: 'DESIGNER',
  lounge: 'LOUNGE',
  brideSmaid: 'BRIDESMAID',
  bussinessCausal: 'BUSINESS CASUAL',
  nightOut: 'NIGHTOUT',
  professional: 'PROFESSIONAL',
  skiTrip: 'SKI TRIP',
  weddingEvent: 'WEDDING EVENT',
  workOut: 'WORKOUT',
  apple: 'APPLE',
  athletic: 'ATHLETIC',
  bumpFriendly: 'BUMP FRIENDLY',
  fullBlast: 'FULL BUST',
  hourGlass: 'HOURGLASS',
  pear: 'PEAR',
  pettite: 'PETITE',
  straightAndNarrow: 'STRAIGHT & NARROW',
  returnToMainMenu: 'RETURN TO MAIN MENU',
  animal: 'ANIMAL',
  embellished: 'EMBELLISHED',
  floral: 'FLORAL',
  geometric: 'GEOMETRIC',
  gingham: 'GINGHAM',
  priented: 'PRINTED',
  stripes: 'STRIPES',
  tyeDye: 'TYE DYE',
  lace: 'LACE ',
  leather: 'LEATHER',
  velvet: 'VELVET',
  sequins: 'SEQUINS',
  suede: 'SUEDE',
  backLess: 'BACKLESS ',
  bodyCon: 'BODYCON',
  bustier: 'BUSTIER',
  casual: 'CASUAL',
  denim: 'DENIM',
  fitted: 'FITTED',
  fitAndFlare: 'FIT & FLARE',
  hiLow: 'HI-LOW',
  kneeLength: 'KNEE LENGTH',
  longSleeve: 'LONG SLEEVE',
  maxi: 'MAXI',
  midi: 'MIDI',
  strapLess: 'STRAPLESS',
  mini: 'MINI',
  pastels: 'PASTELS',
  wrap: 'WRAP',
  slipDress: 'SLIP DRESS',
  shiftDress: 'SHIFT DRESS',
  springDress: 'SPRING DRESS',
  sunDress: 'SUNDRESS',
  offTheShoulder: 'OFF-THE-SHOULDER',
  shortSleeve: 'SHORT SLEEVE ',
  sleeveLess: 'SLEEVELESS ',
  all: 'ALL',
  reachedEndOfFeed: 'Reached end of feed',
  needMoreInspriation: 'Need More Inspriation?',
  mostLoved: 'Most Loved',
  whatsNew: "What's New",
  shopAll: 'Shop All',
  shopByOccassion: 'Shop by Occassion',
  brandsWeLove: 'BRANDS\nWE\nLOVE',
  recent: 'RECENT',
  savedSearches: 'SAVED SEARCHES',
  manageSearches: 'Manage Searches',
  popular: 'POPULAR',
  searchResultsDetail:
    'Chanel white dress\nGet notified if this item is posted',
  delete: 'DELETE',
  orderDetails: 'ORDER DETAILS',
  yourTransaction: 'YOUR TRANSACTIONS',
  internetUnavailable: 'Internet Unavailable!',
  checkConnection: 'Please check your internet connection.',
  tryAgain: 'Try Again',
  home: 'HOME',
  noMessageAvailable: 'No message available',
  messages: 'Messages',
  originalRetail: 'Original Retail',
};
